version: "3.7"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - ${DEMO_PG_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: postgres
  app:
    image: prueba:latest
    ports:
    - ${DEMO_WEB_PORT:-8080}:8080
    build:
      context: .
    volumes:
      - .:/app
    command: mvn spring-boot:run
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo_development
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      PORT: ${DEMO_WEB_PORT:-8080}